import { enemyData } from './enemy-data.js';

export const scenarioEnemies = {
	1: ['banditGuard', 'banditArcher', 'livingBones'],
	2: ['banditArcher', 'banditCommanderBoss', 'livingBones', 'livingCorpse'],
	3: ['inoxGuard', 'inoxArcher', 'inoxShaman'],
	4: ['livingBones', 'banditArcher', 'cultist', 'earthDemon', 'windDemon'],
	5: ['cultist', 'livingBones', 'nightDemon', 'flameDemon', 'frostDemon'],
	6: ['livingBones', 'livingCorpse', 'livingSpirit'],
	7: ['forestImp', 'caveBear', 'inoxShaman', 'earthDemon'],
	8: ['livingBones', 'livingCorpse', 'inoxBodyguardBoss'],
	9: ['hound', 'vermlingScout', 'mercilessOverseerBoss'],
	10: ['flameDemon', 'earthDemon', 'sunDemon'],
	11: ['livingBones', 'livingCorpse', 'cityGuard', 'cityArcher', 'captainOfTheGuardBoss'],
	12: ['livingBones', 'livingCorpse', 'cultist', 'cityGuard', 'cityArcher', 'jekserahBoss'],
	13: ['stoneGolem', 'caveBear', 'livingSpirit', 'spittingDrake'],
	14: ['hound', 'livingSpirit', 'frostDemon'],
	15: ['stoneGolem', 'savvasIcestorm', 'frostDemon', 'windDemon', 'harrowerInfester'],
	16: ['earthDemon', 'windDemon', 'inoxGuard', 'inoxArcher'],
	17: ['vermlingScout', 'vermlingShaman', 'caveBear'],
	18: ['giantViper', 'ooze', 'vermlingScout'],
	19: ['cultist', 'livingBones', 'livingSpirit', 'livingCorpse'],
	20: ['livingBones', 'cultist', 'nightDemon', 'livingCorpse', 'jekserahBoss'],
	21: ['sunDemon', 'frostDemon', 'nightDemon', 'windDemon', 'earthDemon', 'flameDemon', 'primeDemonBoss'],
	22: ['livingBones', 'cultist', 'earthDemon', 'flameDemon', 'frostDemon', 'windDemon'],
	23: ['stoneGolem', 'ancientArtillery', 'livingBones', 'livingSpirit'],
	24: ['rendingDrake', 'ooze', 'livingSpirit'],
	25: ['hound', 'rendingDrake', 'spittingDrake'],
	26: ['livingCorpse', 'ooze', 'nightDemon', 'blackImp'],
	27: ['nightDemon', 'windDemon', 'frostDemon', 'sunDemon', 'earthDemon', 'flameDemon'],
	28: ['livingCorpse', 'cultist', 'livingBones', 'nightDemon', 'sunDemon'],
	29: ['livingBones', 'livingCorpse', 'livingSpirit', 'blackImp'],
	30: ['ooze', 'lurker', 'deepTerror'],
	31: ['deepTerror', 'nightDemon', 'blackImp'],
	32: ['harrowerInfester', 'giantViper', 'deepTerror', 'blackImp'],
	33: ['savvasIcestorm', 'savvasLavaflow', 'windDemon', 'frostDemon', 'flameDemon', 'earthDemon'],
	34: ['rendingDrake', 'spittingDrake', 'elderDrakeBoss'],
	35: ['flameDemon', 'frostDemon', 'earthDemon', 'windDemon', 'cityGuard', 'cityArcher', 'captainOfTheGuardBoss'],
	36: ['flameDemon', 'frostDemon', 'earthDemon', 'windDemon', 'cityArcher', 'primeDemonBoss'],
	37: ['lurker', 'deepTerror', 'harrowerInfester'],
	38: ['inoxGuard', 'inoxArcher', 'inoxShaman'],
	39: ['caveBear', 'frostDemon', 'spittingDrake', 'cultist', 'livingBones'],
	40: ['livingCorpse', 'flameDemon', 'caveBear', 'stoneGolem', 'forestImp'],
	41: ['ancientArtillery', 'livingCorpse', 'livingSpirit', 'stoneGolem'],
	42: ['nightDemon', 'windDemon', 'livingSpirit'],
	43: ['flameDemon', 'rendingDrake', 'spittingDrake'],
	44: ['inoxGuard', 'inoxArcher', 'hound', 'inoxShaman'],
	45: ['cityGuard', 'cityArcher', 'hound'],
	46: ['nightDemon', 'frostDemon', 'windDemon', 'savvasIcestorm', 'wingedHorrorBoss'],
	47: ['lurker', 'deepTerror', 'harrowerInfester', 'theSightlessEyeBoss'],
	48: ['forestImp', 'earthDemon', 'harrowerInfester', 'darkRiderBoss'],
	49: ['giantViper', 'cityArcher', 'cityGuard', 'ancientArtillery'],
	50: ['nightDemon', 'sunDemon', 'earthDemon', 'windDemon'],
	51: ['theGloomBoss'],
	52: ['vermlingScout', 'spittingDrake', 'livingCorpse', 'ooze', 'vermlingShaman'],
	53: ['ooze', 'livingCorpse', 'livingSpirit', 'livingBones', 'giantViper'],
	54: ['caveBear', 'livingSpirit', 'frostDemon', 'harrowerInfester'],
	55: [],
	56: ['hound', 'banditArcher', 'rendingDrake', 'banditGuard'],
	57: ['cityGuard', 'cityArcher', 'hound'],
	58: ['earthDemon', 'harrowerInfester', 'blackImp', 'cityGuard'],
	59: ['caveBear', 'hound', 'forestImp'],
	60: ['ooze', 'giantViper', 'hound', 'rendingDrake', 'spittingDrake'],
	61: ['ooze', 'giantViper', 'frostDemon', 'flameDemon'],
	62: ['livingBones', 'livingSpirit'],
	63: ['vermlingScout', 'inoxGuard', 'inoxArcher', 'flameDemon'],
	64: ['ooze', 'forestImp', 'rendingDrake'],
	65: ['vermlingScout', 'hound', 'inoxArcher'],
	66: ['ooze', 'ancientArtillery', 'livingSpirit', 'stoneGolem'],
	67: ['forestImp', 'caveBear', 'stoneGolem'],
	68: ['rendingDrake', 'blackImp', 'giantViper', 'livingCorpse'],
	69: ['vermlingScout', 'stoneGolem', 'vermlingShaman', 'livingSpirit', 'forestImp'],
	70: ['nightDemon', 'windDemon', 'livingSpirit'],
	71: ['spittingDrake', 'windDemon', 'sunDemon'],
	72: ['ooze', 'forestImp', 'giantViper'],
	73: ['hound', 'inoxArcher', 'ancientArtillery', 'inoxGuard', 'inoxShaman'],
	74: ['banditGuard', 'banditArcher', 'lurker', 'deepTerror'],
	75: ['livingBones', 'livingCorpse', 'livingSpirit'],
	76: ['giantViper', 'livingBones', 'nightDemon', 'harrowerInfester'],
	77: ['cityGuard', 'cityArcher', 'stoneGolem', 'hound'],
	78: ['banditGuard', 'banditArcher', 'cultist', 'livingBones', 'blackImp'],
	79: ['stoneGolem', 'giantViper', 'theBetrayerBoss'],
	80: ['cityGuard', 'cityArcher', 'ancientArtillery', 'hound'],
	81: ['nightDemon', 'sunDemon', 'stoneGolem', 'ancientArtillery', 'theColorlessBoss'],
	82: ['earthDemon', 'flameDemon', 'stoneGolem'],
	83: ['hound', 'cultist', 'livingBones', 'livingSpirit', 'flameDemon'],
	84: ['flameDemon', 'frostDemon', 'earthDemon'],
	85: ['hound', 'blackImp', 'nightDemon', 'sunDemon'],
	86: ['caveBear', 'vermlingShaman', 'vermlingScout', 'lurker'],
	87: ['lurker', 'deepTerror', 'ooze', 'blackImp'],
	88: ['frostDemon', 'ooze', 'lurker'],
	89: ['banditArcher', 'banditGuard', 'cultist', 'giantViper'],
	90: ['earthDemon', 'windDemon', 'nightDemon', 'livingSpirit'],
	91: ['caveBear', 'hound', 'banditGuard', 'banditArcher', 'livingSpirit'],
	92: ['banditGuard', 'banditArcher', 'inoxGuard', 'savvasLavaflow', 'flameDemon', 'earthDemon', 'cityGuard', 'cityArcher'],
	93: ['lurker', 'frostDemon', 'livingSpirit'],
	94: ['hound', 'vermlingScout', 'vermlingShaman', 'caveBear'],
	95: ['deepTerror', 'flameDemon', 'earthDemon', 'savvasLavaflow'],
};

for (const scenarioNumber in scenarioEnemies) {
	for (const enemyId of scenarioEnemies[scenarioNumber]) {
		// TODO: Remove boss check once boss functionality is added
		if (enemyId.includes('Boss')) {
			continue;
		}

		if (!enemyData[enemyId]) {
			console.warn(`Scenario ${scenarioNumber} references enemy ID ${enemyId}, but it wasn't found in enemy data`);
		}
	}
}
